# Python Variables: Mental Model

To really understand how variables work in Python, it's a great idea to have a mental model.
A common mental model when thinking about variables in various programming languages is the "container vs. label":

- _Container_ variable: A variable gets assigned a unique memory location to contain its own data. The variable and the memory location are integral; you cannot have more than one variable referring to the same memory location. Each variable is distinct.
- _Label_ variable: A variable is a _label_ that points to an object in memory. More than one variables (i.e., _labels_) may refer to the _same_ object n memory.

Which of these two models does variables in Python belong to?

## `int`

`int` is, as already shown, a immutable data type in Python.

Consider the following example:

In [67]:
a_int = 53432
b_int = a_int
c_int = b_int

print(f"a_int, type: {type(a_int)}, value: {a_int}, id: {id(a_int)}")
print(f"b_int, type: {type(b_int)}, value: {b_int}, id: {id(b_int)}")
print(f"c_int, type: {type(c_int)}, value: {c_int}, id: {id(c_int)}")

a_int, type: <class 'int'>, value: 53432, id: 2046549359568
b_int, type: <class 'int'>, value: 53432, id: 2046549359568
c_int, type: <class 'int'>, value: 53432, id: 2046549359568


In the above example, the variables `a_int`, `b_int`, and `c_int` refer to the same integer object with a value of `53432`.
Because an `int` is immutable, the value cannot be modified: `1` will always be `1`, `2` will always be `2`, etc.
Furthermore, an `int` object does not have an individual element that can be accessed.

However, the variable can be assigned with a new `int` object of different value:

In [93]:
c_int = 34325235

a new object is created instead (not modified) and assigned to that variable (as indicated by the output of the `id()` function):

In [70]:
print(f"c_int, type: {type(c_int)}, value: {c_int}, id: {id(c_int)}")

c_int, type: <class 'int'>, value: 34325235, id: 2046549360016


If there are other variables refering to the old value, their value remains unchanged.
The old object is still being referred to by the other variables.

In [92]:
print(f"a_int, type: {type(a_int)}, value: {a_int}, id: {id(a_int)}")
print(f"b_int, type: {type(b_int)}, value: {b_int}, id: {id(b_int)}")
print(f"c_int, type: {type(c_int)}, value: {c_int}, id: {id(c_int)}")

a_int, type: <class 'int'>, value: 53432, id: 2046549359568
b_int, type: <class 'int'>, value: 53432, id: 2046549359568
c_int, type: <class 'int'>, value: 34325235, id: 2046549560144


## `float`

`float` is an immutable data type in Python.

In the example below, three variables refer to the same `float` object with value of `53432.0` in the memory as indicated by the results of the `id()` function:

In [87]:
a_float = 53432.0
b_float = a_float
c_float = b_float

print(f"a_float, type: {type(a_float)}, value: {a_float}, id: {id(a_float)}")
print(f"b_float, type: {type(b_float)}, value: {b_float}, id: {id(b_float)}")
print(f"c_float, type: {type(c_float)}, value: {c_float}, id: {id(c_float)}")

a_float, type: <class 'float'>, value: 53432.0, id: 2046549359696
b_float, type: <class 'float'>, value: 53432.0, id: 2046549359696
c_float, type: <class 'float'>, value: 53432.0, id: 2046549359696


A `float` object contains no elements that can be individually accessed. But a variable to a `float` object may be assigned another `float` object, like this:

In [94]:
c_float = 123.05

The variable refers to another object, as indicated by the result of the `id()` function:

In [96]:
print(f"c_float, type: {type(c_float)}, value: {c_float}, id: {id(c_float)}")

c_float, type: <class 'float'>, value: 123.05, id: 2046549358288


But the values of the other variables remain the same:

In [97]:
print(f"a_float, type: {type(a_float)}, value: {a_float}, id: {id(a_float)}")
print(f"b_float, type: {type(b_float)}, value: {b_float}, id: {id(b_float)}")
print(f"c_float, type: {type(c_float)}, value: {c_float}, id: {id(c_float)}")

a_float, type: <class 'float'>, value: 53432.0, id: 2046549359696
b_float, type: <class 'float'>, value: 53432.0, id: 2046549359696
c_float, type: <class 'float'>, value: 123.05, id: 2046549358288


## `str`

`str` is an immutable data type.

In the following example, two variables refer to the same `str` object in memory as indicated by the results of the `id()` function:

In [77]:
a_str = "Hello, World!"
b_str = a_str

print(f"a_str, type: {type(a_str)}, value: {a_str}, id: {id(a_str)}")
print(f"b_str, type: {type(b_str)}, value: {b_str}, id: {id(b_str)}")

a_str, type: <class 'str'>, value: Hello, World!, id: 2046548636784
b_str, type: <class 'str'>, value: Hello, World!, id: 2046548636784


Elements of a `str` object can be accesssed, for example:

In [98]:
a_str[0:5]

'Hello'

However, because `str` data type is immutable, its elements cannot be changed:

In [99]:
a_str[0] = "h"

TypeError: 'str' object does not support item assignment

When one of the above variables is assigned a new object, the variable will refer to the new object and does not affect the other variables:

In [100]:
b_str = "hello, world!"

print(f"a_str, type: {type(a_str)}, value: {a_str}, id: {id(a_str)}")
print(f"b_str, type: {type(b_str)}, value: {b_str}, id: {id(b_str)}")

a_str, type: <class 'str'>, value: Hello, World!, id: 2046548636784
b_str, type: <class 'str'>, value: hello, world!, id: 2046550426864


As indicated by the results of the `id()` function, the two variables now refer to two different objects.

## `list` 

`list` is a mutable data type in Python.

In the example below, three variables refer to the same `list` object in memory as indicated by the results of the `id()` function:

In [101]:
a_list = [1, 2, 3]
b_list = a_list
c_list = b_list

print(f"a_list, type: {type(a_list)} value: {a_list}, id: {id(a_list)}")
print(f"b_list, type: {type(b_list)} value: {b_list}, id: {id(b_list)}")
print(f"c_list, type: {type(c_list)} value: {c_list}, id: {id(c_list)}")

a_list, type: <class 'list'> value: [1, 2, 3], id: 2046549572608
b_list, type: <class 'list'> value: [1, 2, 3], id: 2046549572608
c_list, type: <class 'list'> value: [1, 2, 3], id: 2046549572608


Being mutable, the elements of a mutable object can be modified after its creation:

In [102]:
b_list[0] = 15 

print(f"b_list, type: {type(b_list)} value: {b_list}, id: {id(b_list)}")

b_list, type: <class 'list'> value: [15, 2, 3], id: 2046549572608


As indicated by the result of the `id()` function above, the object is still the same. Furthermore, this modification can also be seen from the other two variables that refer to the same `list` object:

In [103]:
print(f"a_list, type: {type(a_list)} value: {a_list}, id: {id(a_list)}")
print(f"b_list, type: {type(b_list)} value: {b_list}, id: {id(b_list)}")
print(f"c_list, type: {type(c_list)} value: {c_list}, id: {id(c_list)}")

a_list, type: <class 'list'> value: [15, 2, 3], id: 2046549572608
b_list, type: <class 'list'> value: [15, 2, 3], id: 2046549572608
c_list, type: <class 'list'> value: [15, 2, 3], id: 2046549572608


As indicated by the return values of the `id()` function, the variable `a_list`, `b_list`, and `c_list` all still refer to the same object although the object is already modified.

If one of the variables is assigned a new instance of `list`, then the variable will refer to the new object while the other two still refer to the old object.

In [86]:
b_list = [1, 2, 3, 4]  # A new list instance

print(f"a_list, type: {type(a_list)} value: {a_list}, id: {id(a_list)}")
print(f"b_list, type: {type(b_list)} value: {b_list}, id: {id(b_list)}")
print(f"c_list, type: {type(c_list)} value: {c_list}, id: {id(c_list)}")

a_list, type: <class 'list'> value: [15, 2, 3], id: 2046548723456
b_list, type: <class 'list'> value: [1, 2, 3, 4], id: 2046550397824
c_list, type: <class 'list'> value: [15, 2, 3], id: 2046548723456


## `tuple`

`tuple` is an immutable data type in Python.

In the example below, two variables refers to the same `tuple` object:

In [112]:
a_tuple = (1, 2, 3)
b_tuple = a_tuple

print(f"a_tuple, type: {type(a_tuple)}, value: {a_tuple}, id: {id(a_tuple)}")
print(f"b_tuple, type: {type(b_tuple)}, value: {b_tuple}, id: {id(b_tuple)}")

a_tuple, type: <class 'tuple'>, value: (1, 2, 3), id: 2046545051840
b_tuple, type: <class 'tuple'>, value: (1, 2, 3), id: 2046545051840


_immutable_ means that the variable cannot be modified once instantiated, unlike `list`:

In [113]:
a_tuple[0] = 10

TypeError: 'tuple' object does not support item assignment

If one of the variables is assigned a new `tuple` object, the variable will refer to the new object while the other variable will still refer to the old object.

In [114]:
b_tuple = (4, 5, 6)

print(f"a_tuple, type: {type(a_tuple)}, value: {a_tuple}, id: {id(a_tuple)}")
print(f"b_tuple, type: {type(b_tuple)}, value: {b_tuple}, id: {id(b_tuple)}")

a_tuple, type: <class 'tuple'>, value: (1, 2, 3), id: 2046545051840
b_tuple, type: <class 'tuple'>, value: (4, 5, 6), id: 2046545066752


## `dict`

`dict` is a mutable data type in Python.

In [115]:
a_dict = {'a': 1, 'b': 2, 'c': 3}
b_dict = a_dict
c_dict = b_dict

print(f"a_dict, type: {type(a_dict)}, value: {a_dict}, id: {id(a_dict)}")
print(f"b_dict, type: {type(b_dict)}, value: {b_dict}, id: {id(b_dict)}")
print(f"c_dict, type: {type(c_dict)}, value: {c_dict}, id: {id(c_dict)}")

a_dict, type: <class 'dict'>, value: {'a': 1, 'b': 2, 'c': 3}, id: 2046550463360
b_dict, type: <class 'dict'>, value: {'a': 1, 'b': 2, 'c': 3}, id: 2046550463360
c_dict, type: <class 'dict'>, value: {'a': 1, 'b': 2, 'c': 3}, id: 2046550463360


The values of a mutable data type can be modified:

In [109]:
c_dict['d'] = 4

print(f"c_dict, value: {c_dict}, id: {id(c_dict)}")

c_dict, value: {'a': 1, 'b': 2, 'c': 3, 'd': 4}, id: 2046550427008


If multiple variables refered to the same object, then the modification made via one variable can be seen in the other variables as exemplified below:

In [110]:
print(f"a_dict, value: {a_dict}, id: {id(a_dict)}")
print(f"b_dict, value: {b_dict}, id: {id(b_dict)}")
print(f"c_dict, value: {c_dict}, id: {id(c_dict)}")

a_dict, value: {'a': 1, 'b': 2, 'c': 3, 'd': 4}, id: 2046550427008
b_dict, value: {'a': 1, 'b': 2, 'c': 3, 'd': 4}, id: 2046550427008
c_dict, value: {'a': 1, 'b': 2, 'c': 3, 'd': 4}, id: 2046550427008


All the variables referring to the same object in memory has been modified accordingly.

## Summary

**All variables in Python behaves like a _label_**, more than one variables may refer to the same object.

If a variable refers to an immutable object (e.g., `int`, `tuple`, `str`), then the only way to change the value is to assigning a new object to it.
If there are more than one variable referring to the same immutable object, assigning a new object to one of the variables won't change the other variables.

On the other hand, if a variable refers to a mutable object (`list`, `dict`), its value may be modified.
If there are more than one variable referring to the same mutable object, the modification of the value via one of the variables can be seen through all the other variables.

PS: Two objects with two different `id`s are two different objects (regardless of their value), and vice versa. 